### ISSUE TITLE
Crystal Chest from IronChest

### ISSUE THREAD

**Issue by BlindForceCat** [MJRLegends/Space-Astronomy-Feedback-#923]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. Place a crytal chest in your world and watch the modpack not responding and not starting the world anymore
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.6.9

**Where did this bug happen:** [Single Player and Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This is no where near enough information 

> Place a crystal chest in your world and watch the modpack not responding and not starting the world anymore

will not help me look at this issue,
also please try with v1.7.1

**Comment by BlindForceCat** [comment]
How am i supposed to try this in version 1.7.1 when the only supports 1.6.9 you could be so kikd to ask nitrado to change the modpacks version but i sont think they are gonna change anything
-- 
Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 08/08/2017, 18:38 MJRLegends <notifications@github.com> wrote:
This is no where near enough information

Place a crystal chest in your world and watch the modpack not responding and not starting the world anymore

will not help me look at this issue,
also please try with v1.7.1

**Comment by MJRLegends** [comment]
idk who nitrado is.... i dont take bug reports from 2 versions old sorry as its probably already fixed

**Comment by BlindForceCat** [comment]
I dont actually think that the bug is fixed cuz there is no report of it so far so it's your modpack that is getting supported form the most popular server host in germany and you dont even care about the bug causing a server to not even start anymore ??? are you serious ? that's hilarious

 

 

Gesendet: Dienstag, 08. August 2017 um 18:46 Uhr
Von: MJRLegends <notifications@github.com>
An: MJRLegends/Space-Astronomy-Feedback- <Space-Astronomy-Feedback-@noreply.github.com>
Cc: BlindForceCat <premiumgamelp@web.de>, Author <author@noreply.github.com>
Betreff: Re: [MJRLegends/Space-Astronomy-Feedback-] Crystal Chest from IronChest (#923)


idk who nitrado is.... i dont take bug reports from 2 versions old sorry as its probably already fixed

**Comment by MJRLegends** [comment]
The server needs to update, then you can report the bug if its still happening
